name: oca-control
type: php
docroot: api/public
php_version: "8.3"
webserver_type: apache-fpm
database:
  type: mysql
  version: "8.0"
composer_version: "2"
web_environment:
  - APP_ENV=local
  - DB_HOST=db
  - DB_PORT=3306
  - DB_NAME=db
  - DB_USER=db
  - DB_PASSWORD=db
  - API_PREFIX=
nodejs_version: "20"
